### ISSUE TITLE
Issue with repo installation 

### ISSUE THREAD

**Issue by biswassanket** [rossumai/docile#49]
```
docker-compose build jupyter[-gpu]
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.jupyter: 'deploy'
```

The docker option does not work. We also tried to pip install the .whl build but we couldn´t find the file. Could you please take a look 

Thanks in advance.

**Comment by simsa-st** [comment]
Hi @biswassanket, you can download the wheel from https://github.com/rossumai/docile/releases.

For docker compose, did you run it like this: `docker-compose build jupyter` (i.e., without the `[-gpu]` suffix which just means you can either run this or `docker-compose build jupyter-gpu`)? If it does not work, I guess you might have a different version of docker compose. You can remove the deploy section from `docker-compose.yml` or change it so that it works with your version of docker compose.

Did it solve your problem?

**Comment by biswassanket** [comment]
Hi @simsa-st thanks for the quick fix.  I managed to run the pip install successfully now... maybe it would be nice if you mention in the readme :) also it should be "docker-compose"  instead of "docker compose" as mentioned in readme.

**Comment by simsa-st** [comment]
Good point, I will add the link to the releases. I think `docker compose` is just a new syntax for `docker-compose` so that depends on the version you are using..
